/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  NftMarketplaceStorage,
  NftMarketplaceStorageInterface,
} from "../../contracts/NftMarketplaceStorage";

const _abi = [
  {
    inputs: [],
    name: "treasuryData",
    outputs: [
      {
        internalType: "address",
        name: "treasury",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "treasurySellerFeeBPS",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "treasuryBuyerFeeBPS",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NftMarketplaceStorage__factory {
  static readonly abi = _abi;
  static createInterface(): NftMarketplaceStorageInterface {
    return new Interface(_abi) as NftMarketplaceStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NftMarketplaceStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as NftMarketplaceStorage;
  }
}
