/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface EventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "BlockUser"
      | "BuyNft"
      | "CancelListNft"
      | "ListNft"
      | "PlaceBidNft"
      | "TreasuryBuyerFeeSet"
      | "TreasurySellerFeeSet"
      | "TreasurySet"
      | "UnblockUser"
      | "WithdrawLockAmount"
  ): EventFragment;
}

export namespace BlockUserEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyNftEvent {
  export type InputTuple = [
    buyer: AddressLike,
    seller: AddressLike,
    nftContract: AddressLike,
    nftId: BigNumberish,
    amount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    seller: string,
    nftContract: string,
    nftId: bigint,
    amount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    buyer: string;
    seller: string;
    nftContract: string;
    nftId: bigint;
    amount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelListNftEvent {
  export type InputTuple = [
    owner: AddressLike,
    nftContract: AddressLike,
    nftId: BigNumberish
  ];
  export type OutputTuple = [owner: string, nftContract: string, nftId: bigint];
  export interface OutputObject {
    owner: string;
    nftContract: string;
    nftId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListNftEvent {
  export type InputTuple = [
    owner: AddressLike,
    nftContract: AddressLike,
    acceptToken: AddressLike,
    nftId: BigNumberish,
    price: BigNumberish,
    amount: BigNumberish,
    listingCount: BigNumberish,
    nftKind: BigNumberish,
    sellKind: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    nftContract: string,
    acceptToken: string,
    nftId: bigint,
    price: bigint,
    amount: bigint,
    listingCount: bigint,
    nftKind: bigint,
    sellKind: bigint
  ];
  export interface OutputObject {
    owner: string;
    nftContract: string;
    acceptToken: string;
    nftId: bigint;
    price: bigint;
    amount: bigint;
    listingCount: bigint;
    nftKind: bigint;
    sellKind: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlaceBidNftEvent {
  export type InputTuple = [
    oldBidder: AddressLike,
    newBidder: AddressLike,
    nftContract: AddressLike,
    nftId: BigNumberish,
    amount: BigNumberish,
    oldBid: BigNumberish,
    newBid: BigNumberish
  ];
  export type OutputTuple = [
    oldBidder: string,
    newBidder: string,
    nftContract: string,
    nftId: bigint,
    amount: bigint,
    oldBid: bigint,
    newBid: bigint
  ];
  export interface OutputObject {
    oldBidder: string;
    newBidder: string;
    nftContract: string;
    nftId: bigint;
    amount: bigint;
    oldBid: bigint;
    newBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryBuyerFeeSetEvent {
  export type InputTuple = [
    prevTreasuryBuyerFee: BigNumberish,
    newTreasuryBuyerFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    prevTreasuryBuyerFee: bigint,
    newTreasuryBuyerFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    prevTreasuryBuyerFee: bigint;
    newTreasuryBuyerFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySellerFeeSetEvent {
  export type InputTuple = [
    prevTreasurySellerFee: BigNumberish,
    newTreasurySellerFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    prevTreasurySellerFee: bigint,
    newTreasurySellerFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    prevTreasurySellerFee: bigint;
    newTreasurySellerFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [
    prevTreasury: AddressLike,
    newTreasury: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    prevTreasury: string,
    newTreasury: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    prevTreasury: string;
    newTreasury: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnblockUserEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawLockAmountEvent {
  export type InputTuple = [caller: AddressLike, value: BigNumberish];
  export type OutputTuple = [caller: string, value: bigint];
  export interface OutputObject {
    caller: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Events extends BaseContract {
  connect(runner?: ContractRunner | null): Events;
  waitForDeployment(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BlockUser"
  ): TypedContractEvent<
    BlockUserEvent.InputTuple,
    BlockUserEvent.OutputTuple,
    BlockUserEvent.OutputObject
  >;
  getEvent(
    key: "BuyNft"
  ): TypedContractEvent<
    BuyNftEvent.InputTuple,
    BuyNftEvent.OutputTuple,
    BuyNftEvent.OutputObject
  >;
  getEvent(
    key: "CancelListNft"
  ): TypedContractEvent<
    CancelListNftEvent.InputTuple,
    CancelListNftEvent.OutputTuple,
    CancelListNftEvent.OutputObject
  >;
  getEvent(
    key: "ListNft"
  ): TypedContractEvent<
    ListNftEvent.InputTuple,
    ListNftEvent.OutputTuple,
    ListNftEvent.OutputObject
  >;
  getEvent(
    key: "PlaceBidNft"
  ): TypedContractEvent<
    PlaceBidNftEvent.InputTuple,
    PlaceBidNftEvent.OutputTuple,
    PlaceBidNftEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryBuyerFeeSet"
  ): TypedContractEvent<
    TreasuryBuyerFeeSetEvent.InputTuple,
    TreasuryBuyerFeeSetEvent.OutputTuple,
    TreasuryBuyerFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySellerFeeSet"
  ): TypedContractEvent<
    TreasurySellerFeeSetEvent.InputTuple,
    TreasurySellerFeeSetEvent.OutputTuple,
    TreasurySellerFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;
  getEvent(
    key: "UnblockUser"
  ): TypedContractEvent<
    UnblockUserEvent.InputTuple,
    UnblockUserEvent.OutputTuple,
    UnblockUserEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawLockAmount"
  ): TypedContractEvent<
    WithdrawLockAmountEvent.InputTuple,
    WithdrawLockAmountEvent.OutputTuple,
    WithdrawLockAmountEvent.OutputObject
  >;

  filters: {
    "BlockUser(address,uint40)": TypedContractEvent<
      BlockUserEvent.InputTuple,
      BlockUserEvent.OutputTuple,
      BlockUserEvent.OutputObject
    >;
    BlockUser: TypedContractEvent<
      BlockUserEvent.InputTuple,
      BlockUserEvent.OutputTuple,
      BlockUserEvent.OutputObject
    >;

    "BuyNft(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      BuyNftEvent.InputTuple,
      BuyNftEvent.OutputTuple,
      BuyNftEvent.OutputObject
    >;
    BuyNft: TypedContractEvent<
      BuyNftEvent.InputTuple,
      BuyNftEvent.OutputTuple,
      BuyNftEvent.OutputObject
    >;

    "CancelListNft(address,address,uint256)": TypedContractEvent<
      CancelListNftEvent.InputTuple,
      CancelListNftEvent.OutputTuple,
      CancelListNftEvent.OutputObject
    >;
    CancelListNft: TypedContractEvent<
      CancelListNftEvent.InputTuple,
      CancelListNftEvent.OutputTuple,
      CancelListNftEvent.OutputObject
    >;

    "ListNft(address,address,address,uint256,uint256,uint256,uint256,uint8,uint8)": TypedContractEvent<
      ListNftEvent.InputTuple,
      ListNftEvent.OutputTuple,
      ListNftEvent.OutputObject
    >;
    ListNft: TypedContractEvent<
      ListNftEvent.InputTuple,
      ListNftEvent.OutputTuple,
      ListNftEvent.OutputObject
    >;

    "PlaceBidNft(address,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PlaceBidNftEvent.InputTuple,
      PlaceBidNftEvent.OutputTuple,
      PlaceBidNftEvent.OutputObject
    >;
    PlaceBidNft: TypedContractEvent<
      PlaceBidNftEvent.InputTuple,
      PlaceBidNftEvent.OutputTuple,
      PlaceBidNftEvent.OutputObject
    >;

    "TreasuryBuyerFeeSet(uint16,uint16,uint256)": TypedContractEvent<
      TreasuryBuyerFeeSetEvent.InputTuple,
      TreasuryBuyerFeeSetEvent.OutputTuple,
      TreasuryBuyerFeeSetEvent.OutputObject
    >;
    TreasuryBuyerFeeSet: TypedContractEvent<
      TreasuryBuyerFeeSetEvent.InputTuple,
      TreasuryBuyerFeeSetEvent.OutputTuple,
      TreasuryBuyerFeeSetEvent.OutputObject
    >;

    "TreasurySellerFeeSet(uint16,uint16,uint256)": TypedContractEvent<
      TreasurySellerFeeSetEvent.InputTuple,
      TreasurySellerFeeSetEvent.OutputTuple,
      TreasurySellerFeeSetEvent.OutputObject
    >;
    TreasurySellerFeeSet: TypedContractEvent<
      TreasurySellerFeeSetEvent.InputTuple,
      TreasurySellerFeeSetEvent.OutputTuple,
      TreasurySellerFeeSetEvent.OutputObject
    >;

    "TreasurySet(address,address,uint40)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;

    "UnblockUser(address,uint40)": TypedContractEvent<
      UnblockUserEvent.InputTuple,
      UnblockUserEvent.OutputTuple,
      UnblockUserEvent.OutputObject
    >;
    UnblockUser: TypedContractEvent<
      UnblockUserEvent.InputTuple,
      UnblockUserEvent.OutputTuple,
      UnblockUserEvent.OutputObject
    >;

    "WithdrawLockAmount(address,uint256)": TypedContractEvent<
      WithdrawLockAmountEvent.InputTuple,
      WithdrawLockAmountEvent.OutputTuple,
      WithdrawLockAmountEvent.OutputObject
    >;
    WithdrawLockAmount: TypedContractEvent<
      WithdrawLockAmountEvent.InputTuple,
      WithdrawLockAmountEvent.OutputTuple,
      WithdrawLockAmountEvent.OutputObject
    >;
  };
}
